### ISSUE TITLE
Created PCConsoleTOC.bin increases stuttering

### ISSUE THREAD

**Issue by TheEarthrise** [ME3Tweaks/AutoTOC#1] opened 2021-07-11 14:17 UTC
Im playing Mass Effect LE1 right now. The game has some minor stuttering issues while you pass certain spots on the map, seems like the engine is loading or something. If you walk over one of those spots, which are plenty in the game, the FPS are dropping by 1-2 FPS, which is noticeable, but pretty minor, so no big deal. Those drops happen every time you walk over those spots, so you can go back and forward to reproduce them every time.

If I don't change any file, but just recreate the PCConsoleTOC.bin using AutoTOC, those drops going to 7-8 FPS, which translates to huge lags. As soon as I replace the PCConsoleTOC.bin with the original file, the drops a back to 1-2 FPS. The filesize of both files is different. Original is 777 KB while the one created with AutoTOC is 737 KB.

If I install any mod that recreates the PCConsoleTOC.bin, the described behaviour occurs.

I've noticed that the original PCConsoleTOC.bin contains the PCConsoleTOC.bin itself and the PCConsoleTOC.txt. Both are not present in the PCConsoleTOC.bin created with AutoTOC, though I'm not sure if this has anything to do with the increased lags.

**Comment by Mgamerz** [comment] 2021-07-11 14:25
Our implementation of TOC is different from BioWare's. It is a bit less efficient because they use a very strange hash lookup system that we don't use because we aren't sure how to build the lookup table. Long term we might look into it but this isn't a priority for us right now.

**Comment by TheEarthrise** [comment] 2021-07-11 14:33
Hey, thank you for the fast reply. If you want to look into it, here is a screenshot of an early spot. Whenever you cross one of the red lines, the stuttering occurs:
![ME LE1](https://user-images.githubusercontent.com/87270139/125199258-a7d10600-e265-11eb-9266-613fdc798999.jpg)

**Comment by Piet1702** [comment] 2021-07-13 20:58
Omg finally someone with the same problem. 
I searched the internet (and discord) up and down (and up) and did not find anything other than those regular "my game stutters" posts. But this is, as posted from @TheEarthrise, related to the PCConsoleTOC.bin file.

I did the same tests as OP. Added a Mod to MELE1 and the stuttering started. Replaced the PCConsoleTOC.bin with the original one, and the stutter was gone. I now finished MELE1 with only "Script" Mods like Disable Mouse Acceleration and without any Texture Mods because with the stock TOC.bin it's hit or miss if they work correctly.

But now with MELE2 I would really like to use some Texture Mods in the future (especially in MELE3 later on). 
For me though, it's hard to believe that so fewer people are having those kinds of "problems" or are they just not noticing it? I mean the game is out for weeks now and mods are possible for weeks also and thus far this kind of problem hasn't been mentioned elsewhere?

Here are two videos form comparison, as stated above, its always when the game has to "load" something in the background. Pretty reproducible. You have to watch it in fullscreen and monitor the green line on the top right corner.


https://user-images.githubusercontent.com/37221655/125522254-7b4221b6-7382-411b-816a-a903461e99ea.mp4


https://user-images.githubusercontent.com/37221655/125522276-731d26de-3eb2-4256-8377-1dae330b134e.mp4

Background notes:
Game is legit, driver up to date, checked game files, Mod manager up to date, tried different SSD, hardware is plenty.

**Comment by TheEarthrise** [comment] 2021-07-13 21:25
Yeah I searched the internet like you did, but as you said I just found the usual stuttering issues that both of us obviously don't have. I don't understand either how no one else is reporting this issue? Maybe most MELE players just don't mod their game, I don't get it.

I'm running this on a Ryzen 5950X + RTX 3080 @3440x1440 @100 FPS limit, installed on a WD SN850 2TB. Overall the hardware utilization is pretty low so this can't be an issue. I thought the fault is on my end since I didn't find someone else with this problem.

I did a lot of testing:
- Upgraded my Windows 10, installed every new driver I could find
- Tried different PCs with different hardware
- Installed a fresh windows 10 21H1
- Installed a fresh VMware Workstation v16 VM and played it in the VM, since I thought nVidias drivers could be an issue

The problem stayed, no matter what, as soon as I installed any mod. Right now I'm using Flawless Widescreen for FOV change, since it's the only possible way to play without those loading stutters.

**Comment by Mgamerz** [comment] 2021-07-16 23:15
Thanks for the detailed reports. Did some work today and our implementation should now be nearly identical to BioWare's. It'll take a bit before it rolls out as there are 3 implementations of TOC and only 1 has been updated.

If you want to help test please come to the ME3Tweaks Discord.

**Comment by Piet1702** [comment] 2021-07-17 22:51
Hi there. I'm not a frequent discord user. I dont know in which channel I should have posted my "testing" but I just used the updated AutoTOC.asi v2 from here https://github.com/SirCxyrtyx/AutoTOC-asi and the related binkw64 dlls noted in the release notes and its working flawless. No stuttering at all anymore with 8+ mods active. I will continue playing the game tomorrow and if needed can give some more feedback but thus far walked across the whole Normandy (MELE2) without any stuttering. With that said, thanks a ton :)

**Comment by Mgamerz** [comment] 2021-07-17 23:31
The other implementations just updated so it is good to see that it fixes
stutters.

**Comment by henbagle** [comment] 2021-07-18 01:49
Since there are reports that the new implementation fixes the stuttering problem, and the implementation has been updated in all three locations, I am closing this issue. 

Thanks for the report!

**Closed as completed by henbagle** 2021-07-18 01:49 UTC
